# Pandas

In [1]:
import pandas as pd
import numpy as np
print("Pandas version:",pd.__version__)
print("Numpy version:",np.__version__)

import sys
print ("Python version:", sys.version)

Pandas version: 0.20.1
Numpy version: 1.12.1
Python version: 3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]


### Pandas Series objects

In [2]:
data = pd.Series([5, 10, 15, 20, 25])
data

0     5
1    10
2    15
3    20
4    25
dtype: int64

In [3]:
# to access the values of pandas series
data.values

array([ 5, 10, 15, 20, 25])

In [4]:
# access the index of pandas series
data.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
# access data via associated index
print(data[1])
print('--------')
print(data[3:5])

10
--------
3    20
4    25
dtype: int64


In [6]:
#index need not be an integer
dt = pd.Series([1, 2, 3, 4, 5],
              index=['a', 'b', 'c', 'd', 'e'])
dt

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [7]:
# access the data as expected 
dt['c']

3

In [8]:
# Series as specialized dictionary
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64

In [9]:
population['California']

38332521

In [10]:
# unlike dictionary, Series support slicing
population['California' : 'Illinous']

California    38332521
Florida       19552860
Illinois      12882135
dtype: int64

#### Constracting Series objects (pd.Series(data, index=index))

In [11]:
# 1- from a list or numpy array
pd.Series([1, 2, 4])

0    1
1    2
2    4
dtype: int64

In [12]:
# 2a- from a dictionary
pd.Series({1:'a', 5:'c' , 2:'g'}, index=[1,5,2])

1    a
5    c
2    g
dtype: object

In [13]:
# 2b- from a dictionary
pd.Series({'a': 1, 'c':5, 'b':67}, index=['a','b','c'])

a     1
b    67
c     5
dtype: int64

### Pandas DataFrame object

In [14]:
# lets create another pandas series object first
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
dtype: int64

In [15]:
# use dictionary to create a DataFrame from population and area Series objects
states = pd.DataFrame({'population': population , 'area':area})
states

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [16]:
# access the index
states.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

In [17]:
# access column names
states.columns

Index(['area', 'population'], dtype='object')

In [18]:
# access values
states.values

array([[  423967, 38332521],
       [  170312, 19552860],
       [  149995, 12882135],
       [  141297, 19651127],
       [  695662, 26448193]])

In [19]:
# access a column
states['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

#### Constracting DataFrame objects

In [20]:
# 1- from a Series object
pd.DataFrame(population, columns=['population'])

population
California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193

In [21]:
# 2- from a list of dictionary
data = [{'a': 1, 'b':2}
       for i in range(3)]
pd.DataFrame(data)

a  b
0  1  2
1  1  2
2  1  2

In [22]:
# 3- from a dictionary of Series object
pd.DataFrame({'population':population , 'area':area})

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [23]:
# 4- from 2d Numpy array
pd.DataFrame(np.random.rand(3,2),
            columns=['aaa', 'bbb'],
            index=['a','b','c'])

aaa       bbb
a  0.701638  0.008748
b  0.328646  0.587480
c  0.900514  0.698736

### Pandas Index object

In [24]:
ind = pd.Index([1,2,5,16])
ind

Int64Index([1, 2, 5, 16], dtype='int64')

In [25]:
# access index values
ind[3]

16

In [26]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

4 (4,) 1 int64


In [27]:
# indexes are immutable. code below would throw an error message
#ind[3] = 0

## Data Indexing and Selection

In [28]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [29]:
data['b']

0.5

In [30]:
'a' in data

True

In [31]:
1.0 in data

False

In [32]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [33]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [34]:
# assign a new index and an index value
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [35]:
# slicing explicitly
data['b':'e']

b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [36]:
# slicing implicitly
data[0:2]

a    0.25
b    0.50
dtype: float64

In [37]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [38]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [39]:
data.loc['a']

0.25

In [40]:
data.loc[['a', 'c']]

a    0.25
c    0.75
dtype: float64

In [41]:
data.loc['a':'d']

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [42]:
data.iloc[1]

0.5

In [43]:
data.iloc[1:3]

b    0.50
c    0.75
dtype: float64

### Data Selection in DataFrames

In [44]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'population':pop})
data

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [45]:
# access the individual Series that make up the column
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [46]:
# equivalent code
data.area

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [47]:
data.area is data['area']

True

In [48]:
data.area == data['area']

California    True
Florida       True
Illinois      True
New York      True
Texas         True
Name: area, dtype: bool

In [49]:
data['density'] = data['population'] / data['area']
data

area  population     density
California  423967    38332521   90.413926
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763
New York    141297    19651127  139.076746
Texas       695662    26448193   38.018740

In [50]:
data.values

array([[  4.23967000e+05,   3.83325210e+07,   9.04139261e+01],
       [  1.70312000e+05,   1.95528600e+07,   1.14806121e+02],
       [  1.49995000e+05,   1.28821350e+07,   8.58837628e+01],
       [  1.41297000e+05,   1.96511270e+07,   1.39076746e+02],
       [  6.95662000e+05,   2.64481930e+07,   3.80187404e+01]])

In [51]:
# 2D DataFrame
data.T

California       Florida      Illinois      New York  \
area        4.239670e+05  1.703120e+05  1.499950e+05  1.412970e+05   
population  3.833252e+07  1.955286e+07  1.288214e+07  1.965113e+07   
density     9.041393e+01  1.148061e+02  8.588376e+01  1.390767e+02   

                   Texas  
area        6.956620e+05  
population  2.644819e+07  
density     3.801874e+01

In [52]:
data.values[0]

array([  4.23967000e+05,   3.83325210e+07,   9.04139261e+01])

In [53]:
data.values[1]

array([  1.70312000e+05,   1.95528600e+07,   1.14806121e+02])

In [54]:
data['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [55]:
data

area  population     density
California  423967    38332521   90.413926
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763
New York    141297    19651127  139.076746
Texas       695662    26448193   38.018740

In [56]:
# iloc
data.iloc[1]

area          1.703120e+05
population    1.955286e+07
density       1.148061e+02
Name: Florida, dtype: float64

In [57]:
data.iloc[1:3]

area  population     density
Florida   170312    19552860  114.806121
Illinois  149995    12882135   85.883763

In [58]:
data.iloc[1:3, 0:2]

area  population
Florida   170312    19552860
Illinois  149995    12882135

In [59]:
data.loc['Florida']

area          1.703120e+05
population    1.955286e+07
density       1.148061e+02
Name: Florida, dtype: float64

In [60]:
data.loc[['Florida', 'Illinois']]

area  population     density
Florida   170312    19552860  114.806121
Illinois  149995    12882135   85.883763

In [61]:
data.loc[['Florida','Illinois']][['area']]

area
Florida   170312
Illinois  149995

In [62]:
data.loc['Florida':'Illinois', :'population']

area  population
Florida   170312    19552860
Illinois  149995    12882135

In [63]:
# ix indexer is hybrid of loc and iloc
data.ix[1:3 , :'population']

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  


area  population
Florida   170312    19552860
Illinois  149995    12882135

In [64]:
data.ix[1:3 , ['area', 'population']]

area  population
Florida   170312    19552860
Illinois  149995    12882135

In [65]:
# use masking and fancy indexing with loc
data.loc[data['density'] > 100 , ['area', 'density']]

area     density
Florida   170312  114.806121
New York  141297  139.076746

### Operating on DataFrames

In [66]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [67]:
df = pd.DataFrame(rng.randint(0, 10, (3,4)),
                  columns=['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [68]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [69]:
def expo(x):
    y = np.e ** x
    return y

In [70]:
expo(6)

403.428793492735

In [71]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [72]:
# index alignment
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'Alaska':1723337})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, })

In [73]:
pop / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [74]:
# any missing values are filled in with NaN by default in Python
A = pd.Series([2, 4, 6], index=[0,1,2])
B = pd.Series([1, 3, 5], index=[1,2,3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [75]:
# use fill_value 
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [76]:
# index aligment in DataFrames
A = pd.DataFrame(rng.randint(0, 20, (2,2)),
                columns=list('AB'))
B = pd.DataFrame(rng.randint(0, 10, (3,3)),
                columns=list('BAC'))
A

A   B
0  1  11
1  5   1

In [77]:
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [78]:
A + B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [79]:
# fill the missing values with the mean of all values in A 
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

### Hierarhical Indexing

In [80]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]

In [81]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [82]:
pop = pop.reindex(index)
pop

California  2000   NaN
            2010   NaN
New York    2000   NaN
            2010   NaN
Texas       2000   NaN
            2010   NaN
dtype: float64

In [83]:
# all data for which the second index is 2010
pop[:,2010]

California   NaN
New York     NaN
Texas        NaN
dtype: float64

In [84]:
pop.loc['California']

2000   NaN
2010   NaN
dtype: float64

In [85]:
pop.ix['California', 2010]

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


nan

In [86]:
pop.unstack()

2000  2010
California   NaN   NaN
New York     NaN   NaN
Texas        NaN   NaN

In [87]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

total  under18
California 2000    NaN  9267089
           2010    NaN  9284094
New York   2000    NaN  4687374
           2010    NaN  4318033
Texas      2000    NaN  5906301
           2010    NaN  6879014

### indexing and slicing a MultiIndex

In [88]:
pop_df[pop_df['under18'] > 6000000]

total  under18
California 2000    NaN  9267089
           2010    NaN  9284094
Texas      2010    NaN  6879014

In [89]:
pop.unstack().reset_index()

index  2000  2010
0  California   NaN   NaN
1    New York   NaN   NaN
2       Texas   NaN   NaN

### merge and join

In [90]:
pop = pd.read_csv('data/state-population.csv')
areas = pd.read_csv('data/state-areas.csv')
abbrevs = pd.read_csv('data/state-abbrevs.csv')

In [91]:
print(pop.head()); print(areas.head()); print(abbrevs.head())

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0
        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707
        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA


In [92]:
merged = pd.merge(pop, abbrevs, how='outer', left_on='state/region', right_on='abbreviation')
merged.head()

state/region     ages  year  population    state abbreviation
0           AL  under18  2012   1117489.0  Alabama           AL
1           AL    total  2012   4817528.0  Alabama           AL
2           AL  under18  2010   1130966.0  Alabama           AL
3           AL    total  2010   4785570.0  Alabama           AL
4           AL  under18  2011   1125763.0  Alabama           AL

In [93]:
merged = merged.drop('abbreviation', 1)

In [94]:
merged.head()

state/region     ages  year  population    state
0           AL  under18  2012   1117489.0  Alabama
1           AL    total  2012   4817528.0  Alabama
2           AL  under18  2010   1130966.0  Alabama
3           AL    total  2010   4785570.0  Alabama
4           AL  under18  2011   1125763.0  Alabama

In [95]:
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [96]:
# number of nulls
merged.isnull().sum()

state/region     0
ages             0
year             0
population      20
state           96
dtype: int64

In [97]:
merged[merged['population'].isnull()].head()

state/region     ages  year  population state
2448           PR  under18  1990         NaN   NaN
2449           PR    total  1990         NaN   NaN
2450           PR    total  1991         NaN   NaN
2451           PR  under18  1991         NaN   NaN
2452           PR    total  1993         NaN   NaN

In [98]:
merged.loc[merged['state'].isnull(), 'state/region'].unique()

array(['PR', 'USA'], dtype=object)

In [99]:
merged.loc[merged['state/region']=='PR', 'state'] = 'Puerto Rico'

In [100]:
merged.loc[merged['state/region']=='USA', 'state'] = 'United States'

In [101]:
merged.isnull().sum()

state/region     0
ages             0
year             0
population      20
state            0
dtype: int64

In [102]:
final = pd.merge(merged, areas, on='state', how='left')
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [103]:
final.isnull().sum()

state/region      0
ages              0
year              0
population       20
state             0
area (sq. mi)    48
dtype: int64

In [104]:
final.dropna(inplace=True)

In [105]:
final.head()

state/region     ages  year  population    state  area (sq. mi)
0           AL  under18  2012   1117489.0  Alabama        52423.0
1           AL    total  2012   4817528.0  Alabama        52423.0
2           AL  under18  2010   1130966.0  Alabama        52423.0
3           AL    total  2010   4785570.0  Alabama        52423.0
4           AL  under18  2011   1125763.0  Alabama        52423.0

In [106]:
data2010 = final.query("year==2010 & ages == 'total'" )
data2010.head()

state/region   ages  year  population       state  area (sq. mi)
3             AL  total  2010   4785570.0     Alabama        52423.0
91            AK  total  2010    713868.0      Alaska       656425.0
101           AZ  total  2010   6408790.0     Arizona       114006.0
189           AR  total  2010   2922280.0    Arkansas        53182.0
197           CA  total  2010  37333601.0  California       163707.0

In [119]:
df = pd.DataFrame({'A' : np.random.randint(0, 10, size=4),
                   'B' : np.random.randint(0, 10, size=4)})
df

A  B
0  3  5
1  7  2
2  5  3
3  0  1

In [120]:
df['A'].sum()

15

In [121]:
df['B'].mean()

2.75

In [125]:
df.mean(axis='rows')

A    3.75
B    2.75
dtype: float64

In [129]:
# product of all items
df.prod()

A     0
B    30
dtype: int64

In [108]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [110]:
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [127]:
planets.dropna().describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [128]:
planets.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [131]:
df = pd.DataFrame({'key':['A','B','C','A','B','C'],
                   'data':range(6)}, columns=['key', 'data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [134]:
df.groupby('key')

In [135]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7