### Python lists

In [1]:
# python list holds many python objects
L = list(range(10))
L, type(L), type(L[0])

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], list, int)

In [2]:
L2 = list(str(i) for i in L)
L2, type(L2), type(L2[0])

(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], list, str)

In [3]:
#because of python's dynamic typing, it can hold heterogenous lists
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [4]:
#built-in array module in ptyhon since 3.3
import array
L  = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Creating Numpy arrays

1.np.array to create numpy array from python list

In [5]:
import numpy as np
Pylist = [1, 2, 3]

In [6]:
NumpyList = np.array(Pylist)

In [7]:
NumpyList

array([1, 2, 3])

In [8]:
type(Pylist) , type(NumpyList)

(list, numpy.ndarray)

In [9]:
# declare the type of list 
np.array([1,2,3,4], dtype=float)

array([ 1.,  2.,  3.,  4.])

In [10]:
# multidimensional numpy array
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

2.from scratch 

In [11]:
# create zeros
np.zeros(3, dtype=int)

array([0, 0, 0])

In [12]:
# create 3x5 array filled with 1s
np.ones((3,5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [13]:
# create an array of 5s 
np.full((2,4), 5, dtype=float)

array([[ 5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.]])

In [14]:
#array of linear sequence from 4 to 10 
np.arange(4, 10, 2)

array([4, 6, 8])

In [15]:
# array of evenly spaced values
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [16]:
# uniformly distributed random values between 0 and 1
np.random.random((3,4))

array([[ 0.76441654,  0.144536  ,  0.93421634,  0.75447842],
       [ 0.98321649,  0.73227317,  0.17677438,  0.08909922],
       [ 0.21530713,  0.13757205,  0.22903475,  0.77420557]])

In [17]:
# normally distributed values mean=0, std= 1
np.random.normal(0,1, (2,3))

array([[-0.04753365, -0.10177473,  0.55718297],
       [ 0.4838182 , -2.37461523,  0.25305009]])

In [18]:
# random integer, interval [0, 10)
np.random.randint(0, 10, (2,5))

array([[0, 2, 1, 6, 8],
       [3, 9, 4, 6, 2]])

In [19]:
# identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [20]:
np.random.random_sample((3,4))

array([[ 0.04447811,  0.2092812 ,  0.78157704,  0.26083981],
       [ 0.08434053,  0.32937857,  0.97300658,  0.17184724],
       [ 0.72123529,  0.30020697,  0.67702051,  0.56518881]])

In [21]:
#creare an uninitialized array of three integers. the values will be whatever happens
#already exists in that memory location
np.empty(3)

array([ 1.,  1.,  1.])

### Basics of Numpy Arrays

a. Attributes of arrays

In [22]:
import numpy as np
np.random.seed(0) #to generate the same random array each time this code run
x1 = np.random.randint(10, size=6) #one dimensional array
x2 = np.random.randint(10, size=(3,4)) #two dimensional array
x3 = np.random.randint(10, size=(3,4,5)) #three dimensional array

In [23]:
x1

array([5, 0, 3, 3, 7, 9])

In [24]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [25]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [26]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("x3 data:", x3.data)
print("x3 dtype:", x3.dtype)
print("x3 item:", x3.item)
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 data: <memory at 0x1050aaa98>
x3 dtype: int64
x3 item: <built-in method item of numpy.ndarray object at 0x10a42d210>
x3 itemsize: 8 bytes
x3 nbytes: 480 bytes


b. Array indexing

In [27]:
x1

array([5, 0, 3, 3, 7, 9])

In [29]:
x1[4]

7

In [30]:
x1[-1]

9

In [31]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [35]:
x2[0, 0]

3

In [38]:
# colon is for slicing. see the difference above and below.
x2[0:1]

array([[3, 5, 2, 4]])

In [40]:
x2[1,1]

6

In [41]:
x2[2,-3]

6

In [42]:
# change the values in the array
x2[2,0] = 7
x2[2,1] = 7

In [43]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [7, 7, 7, 7]])