### Python lists

In [1]:
# python list holds many python objects
L = list(range(10))
L, type(L), type(L[0])

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], list, int)

In [2]:
L2 = list(str(i) for i in L)
L2, type(L2), type(L2[0])

(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], list, str)

In [3]:
#because of python's dynamic typing, it can hold heterogenous lists
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [4]:
#built-in array module in ptyhon since 3.3
import array
L  = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Creating Numpy arrays

1.np.array to create numpy array from python list

In [5]:
import numpy as np
Pylist = [1, 2, 3]

In [6]:
NumpyList = np.array(Pylist)

In [7]:
NumpyList

array([1, 2, 3])

In [8]:
type(Pylist) , type(NumpyList)

(list, numpy.ndarray)

In [9]:
# declare the type of list 
np.array([1,2,3,4], dtype=float)

array([ 1.,  2.,  3.,  4.])

In [10]:
# multidimensional numpy array
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

2.from scratch 

In [11]:
# create zeros
np.zeros(3, dtype=int)

array([0, 0, 0])

In [12]:
# create 3x5 array filled with 1s
np.ones((3,5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [13]:
# create an array of 5s 
np.full((2,4), 5, dtype=float)

array([[ 5.,  5.,  5.,  5.],
       [ 5.,  5.,  5.,  5.]])

In [14]:
#array of linear sequence from 4 to 10 
np.arange(4, 10, 2)

array([4, 6, 8])

In [15]:
# array of evenly spaced values
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [16]:
# uniformly distributed random values between 0 and 1
np.random.random((3,4))

array([[ 0.04992222,  0.00983814,  0.39670255,  0.5745239 ],
       [ 0.58029973,  0.12476614,  0.43490424,  0.7673408 ],
       [ 0.57523877,  0.09050273,  0.1035611 ,  0.25910045]])

In [17]:
# normally distributed values mean=0, std= 1
np.random.normal(0,1, (2,3))

array([[-0.24132091,  0.52758772, -0.07924313],
       [-1.17311969, -0.70764984,  0.70898503]])

In [18]:
# random integer, interval [0, 10)
np.random.randint(0, 10, (2,5))

array([[6, 2, 0, 3, 9],
       [8, 5, 2, 1, 8]])

In [19]:
# identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [20]:
np.random.random_sample((3,4))

array([[ 0.10760791,  0.46000456,  0.56250295,  0.00772491],
       [ 0.95813712,  0.07696392,  0.08197732,  0.94912254],
       [ 0.70567191,  0.2164082 ,  0.68721147,  0.44370333]])

In [21]:
#creare an uninitialized array of three integers. the values will be whatever happens
#already exists in that memory location
np.empty(3)

array([ 1.,  1.,  1.])

### Basics of Numpy Arrays

a. Attributes of arrays

In [22]:
import numpy as np
np.random.seed(0) #to generate the same random array each time this code run
x1 = np.random.randint(10, size=6) #one dimensional array
x2 = np.random.randint(10, size=(3,4)) #two dimensional array
x3 = np.random.randint(10, size=(3,4,5)) #three dimensional array

In [23]:
x1

array([5, 0, 3, 3, 7, 9])

In [24]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [25]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [26]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print("x3 data:", x3.data)
print("x3 dtype:", x3.dtype)
print("x3 item:", x3.item)
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
x3 data: <memory at 0x10fba0b88>
x3 dtype: int64
x3 item: <built-in method item of numpy.ndarray object at 0x114f23490>
x3 itemsize: 8 bytes
x3 nbytes: 480 bytes


b. Array indexing

In [27]:
x1

array([5, 0, 3, 3, 7, 9])

In [28]:
x1[4]

7

In [29]:
x1[-1]

9

In [30]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [31]:
x2[0, 0]

3

In [32]:
# colon is for slicing. see the difference above and below.
x2[0:1]

array([[3, 5, 2, 4]])

In [33]:
x2[1,1]

6

In [34]:
x2[2,-3]

6

In [35]:
# change the values in the array
x2[2,0] = 7
x2[2,1] = 7

In [36]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [7, 7, 7, 7]])

c. Array slicing x[start : stop : step] default values 0

In [37]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x[:5] #first 5 elements

array([0, 1, 2, 3, 4])

In [39]:
x[::2] #every other element

array([0, 2, 4, 6, 8])

In [40]:
x[1::2] #every other element starting from 1

array([1, 3, 5, 7, 9])

In [41]:
np.arange(1,10, 2) #example of arange method

array([1, 3, 5, 7, 9])

In [42]:
x[::-1] #all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
# Multidimensional subarrays
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [7, 7, 7, 7]])

In [44]:
x2[0] #first row

array([3, 5, 2, 4])

In [45]:
x2[2] #third row

array([7, 7, 7, 7])

In [46]:
x2[2:] == x2[2]

array([[ True,  True,  True,  True]], dtype=bool)

In [47]:
x2[1:2, 1:3] #second row intersection between second and third column

array([[6, 8]])

In [48]:
x2[::-1, ::-1] #can be reversed

array([[7, 7, 7, 7],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [49]:
x2[:,0] #first column

array([3, 7, 7])

In [50]:
# copying feature 
x2_sub = x2[:2 , :2]
x2_sub

array([[3, 5],
       [7, 6]])

In [51]:
x2_sub[0,0] = 61
x2_sub

array([[61,  5],
       [ 7,  6]])

In [52]:
# modifying subarray affects the original array as well
x2

array([[61,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 7,  7,  7,  7]])

In [53]:
#use copy method to keep the original array not updated
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[61,  5],
       [ 7,  6]])

In [54]:
x2_sub_copy[0,0] = 99
x2_sub_copy

array([[99,  5],
       [ 7,  6]])

In [55]:
x2

array([[61,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 7,  7,  7,  7]])

d. Reshaping of arrays

In [56]:
# use reshape method 
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
# convert one dimensional array into two dimensional row or column matrix
y = np.array([1,2,3])
y

array([1, 2, 3])

In [58]:
# row vector via reshape
y.reshape((1,3))

array([[1, 2, 3]])

In [59]:
#row vector via newaxis  
y[np.newaxis, :]

array([[1, 2, 3]])

In [60]:
# column vector via reshape
y.reshape((3,1))

array([[1],
       [2],
       [3]])

In [61]:
#column vector via newaxis 
y[:, np.newaxis]

array([[1],
       [2],
       [3]])

e. Array concatination and splitting

In [62]:
x = np.array([1,2,3])
y = np.array([1,2,3])
z = np.array([61,61,61])

In [63]:
# use np.concatinate
np.concatenate([x,y,z])

array([ 1,  2,  3,  1,  2,  3, 61, 61, 61])

In [64]:
# concat two dimensional arrays
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
np.concatenate([grid, grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [67]:
# vertical stack with vstack
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
k = np.array([[99], [99], [99]])
k

array([[99],
       [99],
       [99]])

In [69]:
# horizontal stack with hstack
np.hstack([k, grid])

array([[99,  1,  2,  3],
       [99,  4,  5,  6],
       [99,  7,  8,  9]])

In [70]:
# splitting of arrays
sp = np.arange(10)
sp

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
x1, x2, x3 = np.split(sp, [1, 3])
x1 , x2, x3

(array([0]), array([1, 2]), array([3, 4, 5, 6, 7, 8, 9]))

In [72]:
four = np.arange(16).reshape((4,4))
four

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
f1, f2 = np.vsplit(four,[2] )
f1, f2

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))