### Python lists

In [1]:
# python list holds many python objects
L = list(range(10))
L, type(L), type(L[0])

([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], list, int)

In [2]:
L2 = list(str(i) for i in L)
L2, type(L2), type(L2[0])

(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], list, str)

In [3]:
#because of python's dynamic typing, it can hold heterogenous lists
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [4]:
#built-in array module in ptyhon since 3.3
import array
L  = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Creating Numpy arrays

1.np.array to create numpy array from python list

In [5]:
import numpy as np
Pylist = [1, 2, 3]

In [6]:
NumpyList = np.array(Pylist)

In [7]:
NumpyList

array([1, 2, 3])

In [8]:
type(Pylist) , type(NumpyList)

(list, numpy.ndarray)

In [9]:
# declare the type of list 
np.array([1,2,3,4], dtype=float)

array([ 1.,  2.,  3.,  4.])

In [10]:
# multidimensional numpy array
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

2.from scratch 

In [11]:
# create zeros
np.zeros(3, dtype=int)

array([0, 0, 0])

In [12]:
# create 3x5 array filled with 1s
np.ones((3,5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])